/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.scryfall.api.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Catalog model.
 */
public class Catalog {
    /**
     * The totalItems property.
     */
    @JsonProperty(value = "total_items")
    private Integer totalItems;

    /**
     * The data property.
     */
    @JsonProperty(value = "data")
    private List<String> data;

    /**
     * Get the totalItems value.
     *
     * @return the totalItems value
     */
    public Integer totalItems() {
        return this.totalItems;
    }

    /**
     * Set the totalItems value.
     *
     * @param totalItems the totalItems value to set
     * @return the Catalog object itself.
     */
    public Catalog withTotalItems(Integer totalItems) {
        this.totalItems = totalItems;
        return this;
    }

    /**
     * Get the data value.
     *
     * @return the data value
     */
    public List<String> data() {
        return this.data;
    }

    /**
     * Set the data value.
     *
     * @param data the data value to set
     * @return the Catalog object itself.
     */
    public Catalog withData(List<String> data) {
        this.data = data;
        return this;
    }

}
