/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.scryfall.api.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for Rarity.
 */
public enum Rarity {
    /** Enum value common. */
    COMMON("common"),

    /** Enum value uncommon. */
    UNCOMMON("uncommon"),

    /** Enum value rare. */
    RARE("rare"),

    /** Enum value mythic. */
    MYTHIC("mythic");

    /** The actual serialized value for a Rarity instance. */
    private String value;

    Rarity(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Rarity instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed Rarity object, or null if unable to parse.
     */
    @JsonCreator
    public static Rarity fromString(String value) {
        Rarity[] items = Rarity.values();
        for (Rarity item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
