/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.scryfall.api.models;

import org.joda.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Set model.
 */
public class Set {
    /**
     * The code property.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The mtgoCode property.
     */
    @JsonProperty(value = "mtgo_code")
    private String mtgoCode;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Possible values include: 'core', 'expansion', 'masters', 'masterpiece',
     * 'from_the_vault', 'spellbook', 'premium_deck', 'duel_deck', 'commander',
     * 'planechase', 'conspiracy', 'archenemy', 'vanguard', 'funny', 'starter',
     * 'box', 'promo', 'token', 'memorabilia', 'treasure_chest'.
     */
    @JsonProperty(value = "set_type")
    private SetTypes setType;

    /**
     * The releasedAt property.
     */
    @JsonProperty(value = "released_at")
    private LocalDate releasedAt;

    /**
     * The blockCode property.
     */
    @JsonProperty(value = "block_code")
    private String blockCode;

    /**
     * The block property.
     */
    @JsonProperty(value = "block")
    private String block;

    /**
     * The parentSetCode property.
     */
    @JsonProperty(value = "parent_set_code")
    private String parentSetCode;

    /**
     * The cardCount property.
     */
    @JsonProperty(value = "card_count")
    private Integer cardCount;

    /**
     * The digital property.
     */
    @JsonProperty(value = "digital")
    private Boolean digital;

    /**
     * The foil property.
     */
    @JsonProperty(value = "foil")
    private Boolean foil;

    /**
     * The iconSvgUri property.
     */
    @JsonProperty(value = "icon_svg_uri")
    private String iconSvgUri;

    /**
     * The searchUri property.
     */
    @JsonProperty(value = "search_uri")
    private String searchUri;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the Set object itself.
     */
    public Set withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the mtgoCode value.
     *
     * @return the mtgoCode value
     */
    public String mtgoCode() {
        return this.mtgoCode;
    }

    /**
     * Set the mtgoCode value.
     *
     * @param mtgoCode the mtgoCode value to set
     * @return the Set object itself.
     */
    public Set withMtgoCode(String mtgoCode) {
        this.mtgoCode = mtgoCode;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Set object itself.
     */
    public Set withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the setType value.
     *
     * @return the setType value
     */
    public SetTypes setType() {
        return this.setType;
    }

    /**
     * Set the setType value.
     *
     * @param setType the setType value to set
     * @return the Set object itself.
     */
    public Set withSetType(SetTypes setType) {
        this.setType = setType;
        return this;
    }

    /**
     * Get the releasedAt value.
     *
     * @return the releasedAt value
     */
    public LocalDate releasedAt() {
        return this.releasedAt;
    }

    /**
     * Set the releasedAt value.
     *
     * @param releasedAt the releasedAt value to set
     * @return the Set object itself.
     */
    public Set withReleasedAt(LocalDate releasedAt) {
        this.releasedAt = releasedAt;
        return this;
    }

    /**
     * Get the blockCode value.
     *
     * @return the blockCode value
     */
    public String blockCode() {
        return this.blockCode;
    }

    /**
     * Set the blockCode value.
     *
     * @param blockCode the blockCode value to set
     * @return the Set object itself.
     */
    public Set withBlockCode(String blockCode) {
        this.blockCode = blockCode;
        return this;
    }

    /**
     * Get the block value.
     *
     * @return the block value
     */
    public String block() {
        return this.block;
    }

    /**
     * Set the block value.
     *
     * @param block the block value to set
     * @return the Set object itself.
     */
    public Set withBlock(String block) {
        this.block = block;
        return this;
    }

    /**
     * Get the parentSetCode value.
     *
     * @return the parentSetCode value
     */
    public String parentSetCode() {
        return this.parentSetCode;
    }

    /**
     * Set the parentSetCode value.
     *
     * @param parentSetCode the parentSetCode value to set
     * @return the Set object itself.
     */
    public Set withParentSetCode(String parentSetCode) {
        this.parentSetCode = parentSetCode;
        return this;
    }

    /**
     * Get the cardCount value.
     *
     * @return the cardCount value
     */
    public Integer cardCount() {
        return this.cardCount;
    }

    /**
     * Set the cardCount value.
     *
     * @param cardCount the cardCount value to set
     * @return the Set object itself.
     */
    public Set withCardCount(Integer cardCount) {
        this.cardCount = cardCount;
        return this;
    }

    /**
     * Get the digital value.
     *
     * @return the digital value
     */
    public Boolean digital() {
        return this.digital;
    }

    /**
     * Set the digital value.
     *
     * @param digital the digital value to set
     * @return the Set object itself.
     */
    public Set withDigital(Boolean digital) {
        this.digital = digital;
        return this;
    }

    /**
     * Get the foil value.
     *
     * @return the foil value
     */
    public Boolean foil() {
        return this.foil;
    }

    /**
     * Set the foil value.
     *
     * @param foil the foil value to set
     * @return the Set object itself.
     */
    public Set withFoil(Boolean foil) {
        this.foil = foil;
        return this;
    }

    /**
     * Get the iconSvgUri value.
     *
     * @return the iconSvgUri value
     */
    public String iconSvgUri() {
        return this.iconSvgUri;
    }

    /**
     * Set the iconSvgUri value.
     *
     * @param iconSvgUri the iconSvgUri value to set
     * @return the Set object itself.
     */
    public Set withIconSvgUri(String iconSvgUri) {
        this.iconSvgUri = iconSvgUri;
        return this;
    }

    /**
     * Get the searchUri value.
     *
     * @return the searchUri value
     */
    public String searchUri() {
        return this.searchUri;
    }

    /**
     * Set the searchUri value.
     *
     * @param searchUri the searchUri value to set
     * @return the Set object itself.
     */
    public Set withSearchUri(String searchUri) {
        this.searchUri = searchUri;
        return this;
    }

}
