// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Scryfall.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Colors.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Colors
    {
        [EnumMember(Value = "W")]
        W,
        [EnumMember(Value = "U")]
        U,
        [EnumMember(Value = "B")]
        B,
        [EnumMember(Value = "R")]
        R,
        [EnumMember(Value = "G")]
        G
    }
    internal static class ColorsEnumExtension
    {
        internal static string ToSerializedValue(this Colors? value)
        {
            return value == null ? null : ((Colors)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Colors value)
        {
            switch( value )
            {
                case Colors.W:
                    return "W";
                case Colors.U:
                    return "U";
                case Colors.B:
                    return "B";
                case Colors.R:
                    return "R";
                case Colors.G:
                    return "G";
            }
            return null;
        }

        internal static Colors? ParseColors(this string value)
        {
            switch( value )
            {
                case "W":
                    return Colors.W;
                case "U":
                    return Colors.U;
                case "B":
                    return Colors.B;
                case "R":
                    return Colors.R;
                case "G":
                    return Colors.G;
            }
            return null;
        }
    }
}
