// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Scryfall.API.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Color.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Color
    {
        [EnumMember(Value = "W")]
        W,
        [EnumMember(Value = "U")]
        U,
        [EnumMember(Value = "B")]
        B,
        [EnumMember(Value = "R")]
        R,
        [EnumMember(Value = "G")]
        G
    }
    internal static class ColorEnumExtension
    {
        internal static string ToSerializedValue(this Color? value)
        {
            return value == null ? null : ((Color)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Color value)
        {
            switch( value )
            {
                case Color.W:
                    return "W";
                case Color.U:
                    return "U";
                case Color.B:
                    return "B";
                case Color.R:
                    return "R";
                case Color.G:
                    return "G";
            }
            return null;
        }

        internal static Color? ParseColor(this string value)
        {
            switch( value )
            {
                case "W":
                    return Color.W;
                case "U":
                    return Color.U;
                case "B":
                    return Color.B;
                case "R":
                    return Color.R;
                case "G":
                    return Color.G;
            }
            return null;
        }
    }
}
