// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Scryfall.API.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Ruling
    {
        /// <summary>
        /// Initializes a new instance of the Ruling class.
        /// </summary>
        public Ruling()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Ruling class.
        /// </summary>
        public Ruling(string source = default(string), System.DateTime? publishedAt = default(System.DateTime?), string comment = default(string))
        {
            Source = source;
            PublishedAt = publishedAt;
            Comment = comment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "published_at")]
        public System.DateTime? PublishedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

    }
}
