/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.scryfall.api;

import com.microsoft.rest.RestClient;

/**
 * The interface for ScryfallClient class.
 */
public interface ScryfallClient {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://api.scryfall.com";

    /**
     * Gets the Sets object to access its operations.
     * @return the Sets object.
     */
    Sets sets();

    /**
     * Gets the Cards object to access its operations.
     * @return the Cards object.
     */
    Cards cards();

    /**
     * Gets the Rulings object to access its operations.
     * @return the Rulings object.
     */
    Rulings rulings();

    /**
     * Gets the Symbologys object to access its operations.
     * @return the Symbologys object.
     */
    Symbologys symbologys();

    /**
     * Gets the Catalogs object to access its operations.
     * @return the Catalogs object.
     */
    Catalogs catalogs();

}
