package scryfall

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/azure"
    "net/http"
    "context"
)

// SymbologyClient is the client for the Symbology methods of the Scryfall service.
type SymbologyClient struct {
    BaseClient
}
// NewSymbologyClient creates an instance of the SymbologyClient client.
func NewSymbologyClient() SymbologyClient {
    return NewSymbologyClientWithBaseURI(DefaultBaseURI, )
}

// NewSymbologyClientWithBaseURI creates an instance of the SymbologyClient client.
    func NewSymbologyClientWithBaseURI(baseURI string, ) SymbologyClient {
        return SymbologyClient{ NewWithBaseURI(baseURI, )}
    }

// GetAll sends the get all request.
func (client SymbologyClient) GetAll(ctx context.Context) (result CardSymbolList, err error) {
    req, err := client.GetAllPreparer(ctx)
    if err != nil {
    err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "GetAll", nil , "Failure preparing request")
    return
    }

        resp, err := client.GetAllSender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "GetAll", resp, "Failure sending request")
        return
        }

        result, err = client.GetAllResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "GetAll", resp, "Failure responding to request")
        }

    return
    }

    // GetAllPreparer prepares the GetAll request.
    func (client SymbologyClient) GetAllPreparer(ctx context.Context) (*http.Request, error) {
    preparer := autorest.CreatePreparer(
    autorest.AsGet(),
    autorest.WithBaseURL(client.BaseURI),
    autorest.WithPath("/symbology"))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // GetAllSender sends the GetAll request. The method will close the
    // http.Response Body if it receives an error.
    func (client SymbologyClient) GetAllSender(req *http.Request) (*http.Response, error) {
        return autorest.SendWithSender(client, req,
        autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
            }

    // GetAllResponder handles the response to the GetAll request. The method always
    // closes the http.Response Body.
    func (client SymbologyClient) GetAllResponder(resp *http.Response) (result CardSymbolList, err error) {
        err = autorest.Respond(
        resp,
        client.ByInspecting(),
        azure.WithErrorUnlessStatusCode(http.StatusOK),
        autorest.ByUnmarshallingJSON(&result),
        autorest.ByClosing())
        result.Response = autorest.Response{Response: resp}
            return
    }

// ParseMana sends the parse mana request.
    //
func (client SymbologyClient) ParseMana(ctx context.Context, cost string) (result ManaCost, err error) {
    req, err := client.ParseManaPreparer(ctx, cost)
    if err != nil {
    err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "ParseMana", nil , "Failure preparing request")
    return
    }

        resp, err := client.ParseManaSender(req)
        if err != nil {
        result.Response = autorest.Response{Response: resp}
        err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "ParseMana", resp, "Failure sending request")
        return
        }

        result, err = client.ParseManaResponder(resp)
        if err != nil {
        err = autorest.NewErrorWithError(err, "scryfall.SymbologyClient", "ParseMana", resp, "Failure responding to request")
        }

    return
    }

    // ParseManaPreparer prepares the ParseMana request.
    func (client SymbologyClient) ParseManaPreparer(ctx context.Context, cost string) (*http.Request, error) {
                queryParameters := map[string]interface{} {
        "cost": autorest.Encode("query",cost),
        }

    preparer := autorest.CreatePreparer(
    autorest.AsGet(),
    autorest.WithBaseURL(client.BaseURI),
    autorest.WithPath("/symbology/parse-mana"),
    autorest.WithQueryParameters(queryParameters))
    return preparer.Prepare((&http.Request{}).WithContext(ctx))
    }

    // ParseManaSender sends the ParseMana request. The method will close the
    // http.Response Body if it receives an error.
    func (client SymbologyClient) ParseManaSender(req *http.Request) (*http.Response, error) {
        return autorest.SendWithSender(client, req,
        autorest.DoRetryForStatusCodes(client.RetryAttempts, client.RetryDuration, autorest.StatusCodesForRetry...))
            }

    // ParseManaResponder handles the response to the ParseMana request. The method always
    // closes the http.Response Body.
    func (client SymbologyClient) ParseManaResponder(resp *http.Response) (result ManaCost, err error) {
        err = autorest.Respond(
        resp,
        client.ByInspecting(),
        azure.WithErrorUnlessStatusCode(http.StatusOK,http.StatusCreated),
        autorest.ByUnmarshallingJSON(&result),
        autorest.ByClosing())
        result.Response = autorest.Response{Response: resp}
            return
    }

