# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CardFace(Model):
    """CardFace.

    :param name:
    :type name: str
    :param mana_cost:
    :type mana_cost: str
    :param type_line:
    :type type_line: str
    :param oracle_text:
    :type oracle_text: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'mana_cost': {'key': 'mana_cost', 'type': 'str'},
        'type_line': {'key': 'type_line', 'type': 'str'},
        'oracle_text': {'key': 'oracle_text', 'type': 'str'},
    }

    def __init__(self, name=None, mana_cost=None, type_line=None, oracle_text=None):
        super(CardFace, self).__init__()
        self.name = name
        self.mana_cost = mana_cost
        self.type_line = type_line
        self.oracle_text = oracle_text
