# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class Error(Model):
    """Error.

    :param status:
    :type status: int
    :param code:
    :type code: str
    :param details:
    :type details: str
    :param type:
    :type type: str
    :param warnings:
    :type warnings: list[str]
    """

    _attribute_map = {
        'status': {'key': 'status', 'type': 'int'},
        'code': {'key': 'code', 'type': 'str'},
        'details': {'key': 'details', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'warnings': {'key': 'warnings', 'type': '[str]'},
    }

    def __init__(self, status=None, code=None, details=None, type=None, warnings=None):
        super(Error, self).__init__()
        self.status = status
        self.code = code
        self.details = details
        self.type = type
        self.warnings = warnings


class ErrorException(HttpOperationError):
    """Server responsed with exception of type: 'Error'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(ErrorException, self).__init__(deserialize, response, 'Error', *args)
