# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Set(Model):
    """Set.

    :param code:
    :type code: str
    :param mtgo_code:
    :type mtgo_code: str
    :param name:
    :type name: str
    :param set_type: Possible values include: 'core', 'expansion', 'masters',
     'masterpiece', 'from_the_vault', 'spellbook', 'premium_deck', 'duel_deck',
     'commander', 'planechase', 'conspiracy', 'archenemy', 'vanguard', 'funny',
     'starter', 'box', 'promo', 'token', 'memorabilia', 'treasure_chest'
    :type set_type: str or ~swagger.models.SetTypes
    :param released_at:
    :type released_at: date
    :param block_code:
    :type block_code: str
    :param block:
    :type block: str
    :param parent_set_code:
    :type parent_set_code: str
    :param card_count:
    :type card_count: int
    :param digital:
    :type digital: bool
    :param foil:
    :type foil: bool
    :param icon_svg_uri:
    :type icon_svg_uri: str
    :param search_uri:
    :type search_uri: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'mtgo_code': {'key': 'mtgo_code', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'set_type': {'key': 'set_type', 'type': 'SetTypes'},
        'released_at': {'key': 'released_at', 'type': 'date'},
        'block_code': {'key': 'block_code', 'type': 'str'},
        'block': {'key': 'block', 'type': 'str'},
        'parent_set_code': {'key': 'parent_set_code', 'type': 'str'},
        'card_count': {'key': 'card_count', 'type': 'int'},
        'digital': {'key': 'digital', 'type': 'bool'},
        'foil': {'key': 'foil', 'type': 'bool'},
        'icon_svg_uri': {'key': 'icon_svg_uri', 'type': 'str'},
        'search_uri': {'key': 'search_uri', 'type': 'str'},
    }

    def __init__(self, code=None, mtgo_code=None, name=None, set_type=None, released_at=None, block_code=None, block=None, parent_set_code=None, card_count=None, digital=None, foil=None, icon_svg_uri=None, search_uri=None):
        super(Set, self).__init__()
        self.code = code
        self.mtgo_code = mtgo_code
        self.name = name
        self.set_type = set_type
        self.released_at = released_at
        self.block_code = block_code
        self.block = block
        self.parent_set_code = parent_set_code
        self.card_count = card_count
        self.digital = digital
        self.foil = foil
        self.icon_svg_uri = icon_svg_uri
        self.search_uri = search_uri
