/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Cards
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the ScryfallClient.
 */
export interface Cards {


    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.page]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Array>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getAllWithHttpOperationResponse(options?: { page? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card[]>>;

    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {number} [options.page]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Array} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Array} [result]   - The deserialized result object if an error did not occur.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getAll(options?: { page? : number, customHeaders? : { [headerName: string]: string; } }): Promise<models.Card[]>;
    getAll(callback: ServiceCallback<models.Card[]>): void;
    getAll(options: { page? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card[]>): void;


    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.q]
     *
     * @param {string} [options.unique] Possible values include: 'cards', 'art',
     * 'prints'
     *
     * @param {string} [options.order] Possible values include: 'name', 'set',
     * 'rarity', 'color', 'usd', 'tix', 'eur', 'cmc', 'power', 'toughness',
     * 'edhrec', 'artist'
     *
     * @param {string} [options.dir] Possible values include: 'auto', 'asc', 'desc'
     *
     * @param {boolean} [options.includeExtras]
     *
     * @param {number} [options.page]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<List>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    searchWithHttpOperationResponse(options?: { q? : string, unique? : string, order? : string, dir? : string, includeExtras? : boolean, page? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.List>>;

    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.q]
     *
     * @param {string} [options.unique] Possible values include: 'cards', 'art',
     * 'prints'
     *
     * @param {string} [options.order] Possible values include: 'name', 'set',
     * 'rarity', 'color', 'usd', 'tix', 'eur', 'cmc', 'power', 'toughness',
     * 'edhrec', 'artist'
     *
     * @param {string} [options.dir] Possible values include: 'auto', 'asc', 'desc'
     *
     * @param {boolean} [options.includeExtras]
     *
     * @param {number} [options.page]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {List} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {List} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link List} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    search(options?: { q? : string, unique? : string, order? : string, dir? : string, includeExtras? : boolean, page? : number, customHeaders? : { [headerName: string]: string; } }): Promise<models.List>;
    search(callback: ServiceCallback<models.List>): void;
    search(options: { q? : string, unique? : string, order? : string, dir? : string, includeExtras? : boolean, page? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.List>): void;


    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.exact]
     *
     * @param {string} [options.fuzzy]
     *
     * @param {string} [options.set]
     *
     * @param {string} [options.format]
     *
     * @param {string} [options.face]
     *
     * @param {string} [options.version]
     *
     * @param {boolean} [options.pretty]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getNamedWithHttpOperationResponse(options?: { exact? : string, fuzzy? : string, set? : string, format? : string, face? : string, version? : string, pretty? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.exact]
     *
     * @param {string} [options.fuzzy]
     *
     * @param {string} [options.set]
     *
     * @param {string} [options.format]
     *
     * @param {string} [options.face]
     *
     * @param {string} [options.version]
     *
     * @param {boolean} [options.pretty]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getNamed(options?: { exact? : string, fuzzy? : string, set? : string, format? : string, face? : string, version? : string, pretty? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getNamed(callback: ServiceCallback<models.Card>): void;
    getNamed(options: { exact? : string, fuzzy? : string, set? : string, format? : string, face? : string, version? : string, pretty? : boolean, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;


    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.q]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Catalog>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    autocompleteWithHttpOperationResponse(options?: { q? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Catalog>>;

    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {string} [options.q]
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Catalog} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Catalog} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Catalog} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    autocomplete(options?: { q? : string, customHeaders? : { [headerName: string]: string; } }): Promise<models.Catalog>;
    autocomplete(callback: ServiceCallback<models.Catalog>): void;
    autocomplete(options: { q? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Catalog>): void;


    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getRandomWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getRandom(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getRandom(callback: ServiceCallback<models.Card>): void;
    getRandom(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;


    /**
     * @param {number} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getByMultiverseIdWithHttpOperationResponse(id: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {number} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getByMultiverseId(id: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getByMultiverseId(id: number, callback: ServiceCallback<models.Card>): void;
    getByMultiverseId(id: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;


    /**
     * @param {number} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getByMtgoIdWithHttpOperationResponse(id: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {number} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getByMtgoId(id: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getByMtgoId(id: number, callback: ServiceCallback<models.Card>): void;
    getByMtgoId(id: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;


    /**
     * @param {string} code
     *
     * @param {number} number
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getByCodeByNumberWithHttpOperationResponse(code: string, number: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {string} code
     *
     * @param {number} number
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getByCodeByNumber(code: string, number: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getByCodeByNumber(code: string, number: number, callback: ServiceCallback<models.Card>): void;
    getByCodeByNumber(code: string, number: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;


    /**
     * @param {uuid} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<Card>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    getByIdWithHttpOperationResponse(id: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.Card>>;

    /**
     * @param {uuid} id
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {Card} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {Card} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link Card} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    getById(id: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.Card>;
    getById(id: string, callback: ServiceCallback<models.Card>): void;
    getById(id: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.Card>): void;
}
