# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.service_client import ServiceClient
from msrest import Configuration, Serializer, Deserializer
from .version import VERSION
from .operations.sets_operations import SetsOperations
from .operations.cards_operations import CardsOperations
from . import models


class ScryfallConfiguration(Configuration):
    """Configuration for Scryfall
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        if not base_url:
            base_url = 'https://api.scryfall.com'

        super(ScryfallConfiguration, self).__init__(base_url)

        self.add_user_agent('scryfall/{}'.format(VERSION))


class Scryfall(object):
    """Scryfall

    :ivar config: Configuration for client.
    :vartype config: ScryfallConfiguration

    :ivar sets: Sets operations
    :vartype sets: swagger.operations.SetsOperations
    :ivar cards: Cards operations
    :vartype cards: swagger.operations.CardsOperations

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        self.config = ScryfallConfiguration(base_url)
        self._client = ServiceClient(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = 'v1'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)

        self.sets = SetsOperations(
            self._client, self.config, self._serialize, self._deserialize)
        self.cards = CardsOperations(
            self._client, self.config, self._serialize, self._deserialize)
