/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a CardFace.
 */
class CardFace {
  /**
   * Create a CardFace.
   * @member {string} [name]
   * @member {string} [manaCost]
   * @member {string} [typeLine]
   * @member {string} [oracleText]
   */
  constructor() {
  }

  /**
   * Defines the metadata of CardFace
   *
   * @returns {object} metadata of CardFace
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'card_face',
      type: {
        name: 'Composite',
        className: 'CardFace',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          manaCost: {
            required: false,
            serializedName: 'mana_cost',
            type: {
              name: 'String'
            }
          },
          typeLine: {
            required: false,
            serializedName: 'type_line',
            type: {
              name: 'String'
            }
          },
          oracleText: {
            required: false,
            serializedName: 'oracle_text',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CardFace;
