/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Catalog.
 */
class Catalog {
  /**
   * Create a Catalog.
   * @member {number} [totalItems]
   * @member {array} [data]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Catalog
   *
   * @returns {object} metadata of Catalog
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'catalog',
      type: {
        name: 'Composite',
        className: 'Catalog',
        modelProperties: {
          totalItems: {
            required: false,
            serializedName: 'total_items',
            type: {
              name: 'Number'
            }
          },
          data: {
            required: false,
            serializedName: 'data',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Catalog;
