/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a List.
 */
class List {
  /**
   * Create a List.
   * @member {number} [totalCards]
   * @member {boolean} [hasMore]
   * @member {string} [nextPage]
   * @member {array} [data]
   */
  constructor() {
  }

  /**
   * Defines the metadata of List
   *
   * @returns {object} metadata of List
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'list',
      type: {
        name: 'Composite',
        className: 'List',
        modelProperties: {
          totalCards: {
            required: false,
            serializedName: 'total_cards',
            type: {
              name: 'Number'
            }
          },
          hasMore: {
            required: false,
            serializedName: 'has_more',
            type: {
              name: 'Boolean'
            }
          },
          nextPage: {
            required: false,
            serializedName: 'next_page',
            type: {
              name: 'String'
            }
          },
          data: {
            required: false,
            serializedName: 'data',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CardElementType',
                  type: {
                    name: 'Composite',
                    className: 'Card'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = List;
