/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Set.
 */
class Set {
  /**
   * Create a Set.
   * @member {string} [code]
   * @member {string} [mtgoCode]
   * @member {string} [name]
   * @member {string} [setType] Possible values include: 'core', 'expansion',
   * 'masters', 'masterpiece', 'from_the_vault', 'spellbook', 'premium_deck',
   * 'duel_deck', 'commander', 'planechase', 'conspiracy', 'archenemy',
   * 'vanguard', 'funny', 'starter', 'box', 'promo', 'token', 'memorabilia',
   * 'treasure_chest'
   * @member {date} [releasedAt]
   * @member {string} [blockCode]
   * @member {string} [block]
   * @member {string} [parentSetCode]
   * @member {number} [cardCount]
   * @member {boolean} [digital]
   * @member {boolean} [foil]
   * @member {string} [iconSvgUri]
   * @member {string} [searchUri]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Set
   *
   * @returns {object} metadata of Set
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'set',
      type: {
        name: 'Composite',
        className: 'Set',
        modelProperties: {
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          mtgoCode: {
            required: false,
            serializedName: 'mtgo_code',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          setType: {
            required: false,
            serializedName: 'set_type',
            type: {
              name: 'Enum',
              allowedValues: [ 'core', 'expansion', 'masters', 'masterpiece', 'from_the_vault', 'spellbook', 'premium_deck', 'duel_deck', 'commander', 'planechase', 'conspiracy', 'archenemy', 'vanguard', 'funny', 'starter', 'box', 'promo', 'token', 'memorabilia', 'treasure_chest' ]
            }
          },
          releasedAt: {
            required: false,
            serializedName: 'released_at',
            type: {
              name: 'Date'
            }
          },
          blockCode: {
            required: false,
            serializedName: 'block_code',
            type: {
              name: 'String'
            }
          },
          block: {
            required: false,
            serializedName: 'block',
            type: {
              name: 'String'
            }
          },
          parentSetCode: {
            required: false,
            serializedName: 'parent_set_code',
            type: {
              name: 'String'
            }
          },
          cardCount: {
            required: false,
            serializedName: 'card_count',
            type: {
              name: 'Number'
            }
          },
          digital: {
            required: false,
            serializedName: 'digital',
            type: {
              name: 'Boolean'
            }
          },
          foil: {
            required: false,
            serializedName: 'foil',
            type: {
              name: 'Boolean'
            }
          },
          iconSvgUri: {
            required: false,
            serializedName: 'icon_svg_uri',
            type: {
              name: 'String'
            }
          },
          searchUri: {
            required: false,
            serializedName: 'search_uri',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Set;
