/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a SetList.
 */
class SetList {
  /**
   * Create a SetList.
   * @member {array} [data]
   */
  constructor() {
  }

  /**
   * Defines the metadata of SetList
   *
   * @returns {object} metadata of SetList
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'set_list',
      type: {
        name: 'Composite',
        className: 'SetList',
        modelProperties: {
          data: {
            required: false,
            serializedName: 'data',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SetElementType',
                  type: {
                    name: 'Composite',
                    className: 'Set'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = SetList;
